#!/usr/bin/env sh

# コミット対象としてステージ済みのJavaファイルを取得
STAGED_JAVA_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.java$' || true)

# Javaファイルがステージされている場合のみSpotlessを実行
if [ -n "$STAGED_JAVA_FILES" ]; then
  ./mvnw spotless:apply || exit 1

  # 最初からステージされていたJavaファイルだけ再ステージ
  echo "$STAGED_JAVA_FILES" | xargs git add

  ./mvnw spotless:check || exit 1
fi
